export const palettes = {
  blueOcean: '#3669C9',
  orangeFresh: '#FDA429',
  navyBlack: '#13181F',
  white: '#FFFFFF',
  earthGreen: '#3A9B7A',
  redVelvet: '#C93545',
  darkGrey: '#FAFAFA',
  halfGrey: '#838589',
  softGrey: '#EDEDED',
  offGrey: '#FAFAFA',
  offBlue: '#EFF5FB',
  offGreen: '#EEFAF6',
  offRed: '#FCECEF',
};
